# Generated by Django 5.2.4 on 2026-03-11 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_passwordresetcode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresetcode',
            new_name='aplicacion__user_id_1fa2d6_idx',
            old_name='aplicacion_user_id_9b1b7f_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresetcode',
            new_name='aplicacion__expires_8aba4f_idx',
            old_name='aplicacion_expires_9f4a2a_idx',
        ),
    ]
