# Generated by Django 5.2.4 on 2026-03-15 20:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_categoriaproducto_informacionempresa_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id_jugada', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_jugada', models.CharField(max_length=200)),
                ('nivel_dificultad', models.CharField(choices=[('novato', 'Novato'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], default='novato', max_length=20)),
                ('youtube_url', models.URLField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('consejos', models.TextField(blank=True)),
                ('numero_orden', models.PositiveIntegerField(default=1)),
                ('categoria', models.CharField(blank=True, choices=[('yoyos', 'Yoyos'), ('ceros', 'Ceros'), ('fuerza', 'Fuerza'), ('entradas', 'Entradas'), ('giros', 'Giros')], max_length=120)),
                ('requisitos_posteriores', models.TextField(blank=True)),
                ('realizado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'entrenamiento',
                'ordering': ['numero_orden'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioTutorial',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField()),
                ('calificacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_tutoriales', to=settings.AUTH_USER_MODEL)),
                ('jugada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='aplicacion.entrenamiento')),
            ],
            options={
                'db_table': 'comentarios_tutoriales',
                'ordering': ['-created_at'],
            },
        ),
    ]
