# Generated by Django 5.2.4 on 2026-03-17 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_entrenamiento_comentariotutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='url_jugada',
            field=models.URLField(blank=True, null=True),
        ),
    ]
